#!/bin/bash

# change this to get your list of file to be change
array_list=(./test*)

# then it will run a loop
for var in "${array_list[@]}" 
 do
  rm -fr replace*.txt

  # just copy and paste line 13 according to your need
  # sed '[start line to change]~[change every what line] /s[word to change]/[replace word]' [file to change from for loop] > [temporary file] 
  sed '1~3 s/fox/cat/g' $var > replace1.txt &&
  sed '2~3 s/fox/mouse/g' replace1.txt > replace2.txt &&
  sed '3~3 s/fox/turtle/g' replace2.txt > $var.txt
  
 done

# delete temporary file
rm -fr replace*.txt
